### ISSUE TITLE
Dunsany's chess implementation

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#555]
`Chess\Variant\Dunsany\Board` is to be implemented in the [src/Variant](https://github.com/chesslablab/php-chess/tree/main/src/Variant) folder.

Rules:

- Black moves first.
- Only Black's pawns have the two-step option on their first move.
- Black wins by capturing all 32 white pawns; White wins by checkmating Black.

See:

- [Dunsany's chess](https://en.wikipedia.org/wiki/Dunsany%27s_chess)

---
- [x] https://github.com/chesslablab/php-chess/issues/562
- [x] https://github.com/chesslablab/php-chess/issues/564

**Comment by Gardimy** [comment]
**Dunsany's chess offers an intriguing twist on traditional chess by introducing a highly asymmetrical setup. The game challenges the conventional strategies used in regular chess, as Black must navigate through an overwhelming number of White pawns. This setup not only tests Black's tactical skills but also requires creative approaches to piece development and pawn management. On the other hand, White must leverage the sheer number of pawns to create strategic opportunities and aim for checkmate.**

As a Full Stack Web Developer, I find this variant fascinating because it parallels the need for adaptability and innovative problem-solving in software development. Just as Black must maneuver through a complex landscape in Dunsany's chess, developers often encounter intricate and challenging scenarios that require a balance of strategy and creativity.
